# Generated by Django 2.2.5 on 2019-10-01 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clothing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type', models.CharField(max_length=30, verbose_name='Type of clothing:')),
                ('Brand', models.CharField(max_length=30, verbose_name='Brand of item')),
                ('Price', models.CharField(max_length=30, verbose_name='Price of item')),
                ('Description', models.CharField(max_length=255, verbose_name='Description of item')),
            ],
            options={
                'verbose_name': 'Clothing',
                'verbose_name_plural': 'Clothing',
            },
        ),
        migrations.CreateModel(
            name='Shoes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type', models.CharField(max_length=30, verbose_name='Type of shoe:')),
                ('Brand', models.CharField(max_length=30, verbose_name='Brand of shoe')),
                ('Price', models.CharField(max_length=30, verbose_name='Price of shoe')),
                ('Description', models.CharField(max_length=255, verbose_name='Description of shoe')),
            ],
            options={
                'verbose_name': 'Shoe',
                'verbose_name_plural': 'Shoes',
            },
        ),
    ]
