# Generated by Django 2.2.5 on 2019-11-27 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ItemsForSale', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accessories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type', models.CharField(max_length=30, verbose_name='Type of accessory')),
                ('Brand', models.CharField(max_length=30, verbose_name='Brand of accessory')),
                ('Price', models.CharField(max_length=30, verbose_name='Price of accessory')),
                ('Description', models.CharField(max_length=30, verbose_name='Description of accessory.')),
            ],
            options={
                'verbose_name': 'Accessory',
                'verbose_name_plural': 'Accessories',
            },
        ),
    ]
