# Generated by Django 2.2.5 on 2019-11-27 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ItemsForSale', '0002_accessories'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessories',
            name='Picture',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='clothing',
            name='Picture',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='shoes',
            name='Picture',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='accessories',
            name='Description',
            field=models.CharField(max_length=255, verbose_name='Description of accessory.'),
        ),
        migrations.AlterField(
            model_name='clothing',
            name='Brand',
            field=models.CharField(max_length=50, verbose_name='Brand of item'),
        ),
    ]
