# Generated by Django 2.2.5 on 2019-12-07 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ItemsForSale', '0005_auto_20191127_1508'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accessories',
            old_name='Brand',
            new_name='accessory_brand',
        ),
        migrations.RenameField(
            model_name='accessories',
            old_name='Condition',
            new_name='accessory_condition',
        ),
        migrations.RenameField(
            model_name='accessories',
            old_name='Description',
            new_name='accessory_description',
        ),
        migrations.RenameField(
            model_name='accessories',
            old_name='Picture',
            new_name='accessory_picture',
        ),
        migrations.RenameField(
            model_name='accessories',
            old_name='Price',
            new_name='accessory_price',
        ),
        migrations.RenameField(
            model_name='accessories',
            old_name='Type',
            new_name='accessory_type',
        ),
        migrations.RenameField(
            model_name='shoes',
            old_name='Brand',
            new_name='shoe_brand',
        ),
        migrations.RenameField(
            model_name='shoes',
            old_name='Condition',
            new_name='shoe_condition',
        ),
        migrations.RenameField(
            model_name='shoes',
            old_name='Description',
            new_name='shoe_description',
        ),
        migrations.RenameField(
            model_name='shoes',
            old_name='Picture',
            new_name='shoe_picture',
        ),
        migrations.RenameField(
            model_name='shoes',
            old_name='Price',
            new_name='shoe_price',
        ),
        migrations.RenameField(
            model_name='shoes',
            old_name='Type',
            new_name='shoe_type',
        ),
    ]
