# Generated by Django 2.2.5 on 2020-02-07 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ItemsForSale', '0006_auto_20191207_1029'),
    ]

    operations = [
        migrations.CreateModel(
            name='Featured',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('featured_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ItemsForSale.Clothing')),
            ],
        ),
    ]
